POST https://apibarbershop.azurewebsites.net/Clientes/PostClientes
Content-Type: application/json

{
"clienteId": 0,
  "nombre": "Kobe",
  "apellido": "Tejeda",
  "celular": "8097855212",
  "fechaNacimiento": "2022-11-19T16:22:14.425Z",
  "imagen": "none",
  "fechaCreacion": "2022-11-19T16:22:14.425Z",
  "fechaModificacion": "2022-11-19T16:22:14.425Z",
  "status": 0
}